linters:
  disable:
    - godox
    - goerr113
    - golint
    - interfacer
    - ireturn
    - lll
    - maligned
    - scopelint
    - varnamelen
    - wrapcheck
    - wsl
  enable-all: true
issues:
  exclude:
    - "endianness"
    - "G404:"
  exclude-rules:
    - path: backend/tx/lock_table.go
      linters:
        - forcetypeassert
        - ifshort
run:
  skip-files:
    - _test.go
    - testing
    - server.go
