linters:
  disable:
    - golint
    - interfacer
    - maligned
    - scopelint
    - varnamelen
  enable-all: true
issues:
  exclude:
    - "endianness"
    - "G404:"
run:
  skip-files:
    - _test.go
