linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: exported
        arguments: [ "checkPrivateReceivers", "sayRepetitiveInsteadOfStutters" ]
linters:
  disable:
    - godox
    - goerr113
    - golint
    - interfacer
    - ireturn
    - lll
    - maligned
    - scopelint
    - varnamelen
    - wrapcheck
    - wsl
  enable-all: true
issues:
  exclude-use-default: false
  exclude:
    - "endianness"
    - "G404:"
    - "G304:"
    - "stdmethods:"
    - "mnd: Magic number: 2"
    - "SetInt32Record"
  exclude-rules:
    - path: backend/tx/lock_table.go
      linters:
        - forcetypeassert
        - ifshort
run:
  skip-files:
    - _test.go
    - testing
    - server.go
