linters:
  disable:
    - funlen
    - gochecknoglobals
    - goerr113
    - golint
    - gosec
    - interfacer
    - maligned
    - paralleltest
    - scopelint
    - varnamelen
    # - wrapcheck
    - wsl
  enable-all: true
run:
  skip-files:
    - _test.go
