linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: exported
        arguments: [ "checkPrivateReceivers", "sayRepetitiveInsteadOfStutters" ]
linters:
  disable:
    - cyclop
    - dupl
    - exhaustivestruct
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goerr113
    - golint
    - interfacer
    - ireturn
    - lll
    - maligned
    - nestif
    - scopelint
    - varnamelen
    - wrapcheck
    - wsl
    - gocognit
  enable-all: true
issues:
  exclude-use-default: false
  exclude:
    - "endianness"
    - "G304:"
    - "G404:"
    - "mnd: Magic number: 2"
    - "stdmethods:"
    - "Txnum"
  exclude-rules:
    - path: tx/lock_table.go
      linters:
        - forcetypeassert
        - ifshort
    - path: domain/constant.go
      linters:
        - forcetypeassert
    - path: wire.go
      linters:
        - nlreturn
run:
  skip-files:
    - _test.go
    - server.go
    - testing
  skip-dirs:
    - errors
    - sample
