#!/bin/bash

set -eu

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

test_coverage=`mktemp`
coverage_html=docs/coverage
go test -cover ./... -coverprofile=${test_coverage}
${SCRIPT_DIR}/../bin/gcov2lcov -infile=${test_coverage} -outfile=coverage.lcov
genhtml coverage.lcov -o docs/coverage
