// Code generated by MockGen. DO NOT EDIT.
// Source: executor.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/goropikari/simpledbgo/domain"
)

// MockUpdateExecutor is a mock of UpdateExecutor interface.
type MockUpdateExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateExecutorMockRecorder
}

// MockUpdateExecutorMockRecorder is the mock recorder for MockUpdateExecutor.
type MockUpdateExecutorMockRecorder struct {
	mock *MockUpdateExecutor
}

// NewMockUpdateExecutor creates a new mock instance.
func NewMockUpdateExecutor(ctrl *gomock.Controller) *MockUpdateExecutor {
	mock := &MockUpdateExecutor{ctrl: ctrl}
	mock.recorder = &MockUpdateExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateExecutor) EXPECT() *MockUpdateExecutorMockRecorder {
	return m.recorder
}

// ExecuteCreateIndex mocks base method.
func (m *MockUpdateExecutor) ExecuteCreateIndex(arg0 *domain.CreateIndexData, arg1 domain.Transaction) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteCreateIndex", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteCreateIndex indicates an expected call of ExecuteCreateIndex.
func (mr *MockUpdateExecutorMockRecorder) ExecuteCreateIndex(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteCreateIndex", reflect.TypeOf((*MockUpdateExecutor)(nil).ExecuteCreateIndex), arg0, arg1)
}

// ExecuteCreateTable mocks base method.
func (m *MockUpdateExecutor) ExecuteCreateTable(arg0 *domain.CreateTableData, arg1 domain.Transaction) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteCreateTable", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteCreateTable indicates an expected call of ExecuteCreateTable.
func (mr *MockUpdateExecutorMockRecorder) ExecuteCreateTable(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteCreateTable", reflect.TypeOf((*MockUpdateExecutor)(nil).ExecuteCreateTable), arg0, arg1)
}

// ExecuteCreateView mocks base method.
func (m *MockUpdateExecutor) ExecuteCreateView(arg0 *domain.CreateViewData, arg1 domain.Transaction) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteCreateView", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteCreateView indicates an expected call of ExecuteCreateView.
func (mr *MockUpdateExecutorMockRecorder) ExecuteCreateView(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteCreateView", reflect.TypeOf((*MockUpdateExecutor)(nil).ExecuteCreateView), arg0, arg1)
}

// ExecuteDelete mocks base method.
func (m *MockUpdateExecutor) ExecuteDelete(arg0 *domain.DeleteData, arg1 domain.Transaction) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteDelete", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteDelete indicates an expected call of ExecuteDelete.
func (mr *MockUpdateExecutorMockRecorder) ExecuteDelete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteDelete", reflect.TypeOf((*MockUpdateExecutor)(nil).ExecuteDelete), arg0, arg1)
}

// ExecuteInsert mocks base method.
func (m *MockUpdateExecutor) ExecuteInsert(arg0 *domain.InsertData, arg1 domain.Transaction) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteInsert", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteInsert indicates an expected call of ExecuteInsert.
func (mr *MockUpdateExecutorMockRecorder) ExecuteInsert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteInsert", reflect.TypeOf((*MockUpdateExecutor)(nil).ExecuteInsert), arg0, arg1)
}

// ExecuteModify mocks base method.
func (m *MockUpdateExecutor) ExecuteModify(arg0 *domain.ModifyData, arg1 domain.Transaction) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteModify", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteModify indicates an expected call of ExecuteModify.
func (mr *MockUpdateExecutorMockRecorder) ExecuteModify(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteModify", reflect.TypeOf((*MockUpdateExecutor)(nil).ExecuteModify), arg0, arg1)
}
