name: DevEnv

on:
  schedule:
    - cron:  '0 0 */3 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build docker image
      run: docker build -f .devcontainer/Dockerfile -t simpledb .devcontainer/

    - name: docker run
      run: docker run --rm -v $(pwd):/app -w /app simpledb make test
