name: Go

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: tools
      run: make tools

    - name: install psql
      run: sudo apt-get update && sudo apt-get install -y postgresql-client

    - name: lint
      run: make lint

    - name: Test
      run: make ci-test

    - name: e2e Test
      run: make docker-build && bash e2e/test.sh

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success()
      with:
        name: Go Tests
        path: 'report.xml'
        reporter: java-junit
