name: Go

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: tools
      run: make tools

    - name: lint
      run: make lint

    - name: Test
      run: make ci-test

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success()
      with:
        name: Go Tests
        path: 'report.xml'
        reporter: java-junit

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./public
